### PR TITLE
Proposal for PSC guideline changes

### PR DESCRIPTION
**Pull request by m-mohr**
As discussed in the PSC meeting, please vote on it.

### CODE REVIEW

**Comment by aljacob** [comment]
+1

**Review by mkadunc — APPROVED** [review]
+1

**Review by neteler — APPROVED** [review]

**Comment by neteler** [comment]
+1

**Review by edzer — APPROVED** [review]

**Comment by m-mohr** [comment]
+1

Just for me to keep track: @bschumac is missing

**Review by bschumac — APPROVED** [review]

**Comment by m-mohr** [comment]
No, Github is hiding his comment (see more...)

**Comment by m-mohr** [comment]
Note @ all:
There where more ocurrances of the "two business days", which we meant to replace with "five business days". I replaced them after the vote but assume that the intention is clear and we don't need to revote. If you think otherwise, please comment until after the next PSC meeting.

**Pull request merged**
