### PR TITLE
Software review process

### PR DESCRIPTION
**Pull request by m-mohr**
Weakening the software review requirement as discussed in the call. Please vote.

### CODE REVIEW

**Comment by aljacob** [comment]
+1

**Review by neteler — APPROVED** [review]
+1

**Comment by jdries** [comment]
+1

**Comment by edzer** [comment]
+1

**Review by mkadunc — APPROVED** [review]
+1

**Comment by m-mohr** [comment]
+0 (as I'm not sure how fruitful a recommendation is in the end)

Just for me to keep track: @bschumac is missing

**Review by bschumac — APPROVED** [review]

**Pull request merged**
